var cards = [
//Groupe DaRo
	  ["DaRo_cartes1.jpg","Artiste pas facile à contacter"],
	  ["DaRo_cartes2.jpg","Change de chaussettes"],
	  ["DaRo_cartes3.jpg","Crée une forme au hasard"],
	  ["DaRo_cartes4.jpg","Ecoute de la musique Zen"],
	  ["DaRo_cartes5.jpg","Fais un sieste"],
		["DaRo_cartes6.jpg","HOPHiP RVB CMJN"],
		["DaRo_cartes7.jpg","Simple ou basique"],
		["DaRo_cartes8.jpg","Sois plus grossier"],
		["DaRo_cartes9.jpg","Sors du format DIN"],
		["DaRo_cartes10.jpg","Tous les chemins mènent à Romain"],
		["DaRo_cartes11.jpg","Affronte la difficulté"],
		["DaRo_cartes12.jpg","Change de perspective"],
		["DaRo_cartes13.jpg","Coupe internet"],
		["DaRo_cartes14.jpg","Ecoute le vent"],
		["DaRo_cartes15.jpg","Exprime le chaos"],
		["DaRo_cartes16.jpg","La frustration est un signe de qualité"],
		["DaRo_cartes17.jpg","Pile ou face?"],
		["DaRo_cartes18.jpg","Prends un grand verre d'eau"],
		["DaRo_cartes19.jpg","Tourne le à l'envers"],
		["DaRo_cartes20.jpg","Tu es à un trait de la solution"],

//Groupe MaLaNe
	  ["cartes-illustrations_Page_01.jpg","Un café le matin réveille les mouettes"],
	  ["cartes-illustrations_Page_02.jpg","Ce qui fonctionne en noir blanc fonctionne en couleur"],
	  ["cartes-illustrations_Page_03.jpg","Imprime ton travail"],
		["cartes-illustrations_Page_04.jpg","Écoute de la musique classique"],
		["cartes-illustrations_Page_05.jpg","Utilise le premier motif que tu vois"],
		["cartes-illustrations_Page_06.jpg","Fais un acte soudain, destructif et imprévisible, incorpore"],
		["cartes-illustrations_Page_07.jpg","Ferme les yeux"],
		["cartes-illustrations_Page_08.jpg","Fais l’opposé de ce que tu as fait jusque-là"],
		["cartes-illustrations_Page_09.jpg","Lève-toi et change de place"],
		["cartes-illustrations_Page_10.jpg","Fais un brainstorming"],
		["cartes-illustrations_Page_11.jpg","Va dans le minimalisme"],
	  ["cartes-illustrations_Page_12.jpg","Sois plus agressif"],
	  ["cartes-illustrations_Page_13.jpg","Écoute ta musique préférée"],
		["cartes-illustrations_Page_14.jpg","Fais sortir les éléments du cadre"],
		["cartes-illustrations_Page_15.jpg","Inspire-toi du Bauhaus"],
		["cartes-illustrations_Page_16.jpg","Inspire-toi de l’art préhistorique"],
		["cartes-illustrations_Page_17.jpg","Inspire-toi du Constructivisme"],
		["cartes-illustrations_Page_18.jpg","Inspire-toi du Memphis style"],
		["cartes-illustrations_Page_19.jpg","Inspire-toi du Surréalisme"],
		["cartes-illustrations_Page_20.jpg","Écoute de l’ASMR"],
		["cartes-illustrations_Page_21.jpg","Saute 10x sur place"],
		["cartes-illustrations_Page_22.jpg","Écoute une chanson Walt Disney en boucle"],
		["cartes-illustrations_Page_23.jpg","Va sur google Earth"],
		["cartes-illustrations_Page_24.jpg","Fais 5 croquis"],
		["cartes-illustrations_Page_25.jpg","Utilise la transparence"],
		["cartes-illustrations_Page_26.jpg","Scotche-toi la face"],
		["cartes-illustrations_Page_27.jpg","Prends de la distance pour évaluer ton travail"],
		["cartes-illustrations_Page_28.jpg","Imprime toutes tes variantes"],
		["cartes-illustrations_Page_29.jpg","Nettoie ton écran"],


//Groupe NaMi
	  ["nomdufichier.jpg","Demain"],
	  ["nomdufichier.jpg","Sirop de framboise"],
	  ["nomdufichier.jpg","La réponse se trouve au plafond"],
	  ["nomdufichier.jpg","Inspire toi de la météo"],
	  ["nomdufichier.jpg","Noir et blanc"],

//Groupe SaTe
	  ["nomdufichier.jpg","Demain"],
	  ["nomdufichier.jpg","Sirop de framboise"],
	  ["nomdufichier.jpg","La réponse se trouve au plafond"],
	  ["nomdufichier.jpg","Inspire toi de la météo"],
	  ["nomdufichier.jpg","Noir et blanc"],

//Groupe SoMa
	  ["SoMa_01.jpg","Ne complique pas les choses"],
	  ["SoMa_02.jpg","Inspire toi de la météo"],
	  ["SoMa_03.jpg","Mets de la vie dans ton projet "],
	  ["SoMa_04.jpg","Exprime l’harmonie"],
	  ["SoMa_05.jpg","Crois en ta première"],
		["SoMa_06.jpg","N’aie pas peur des clichés"],
	  ["SoMa_07.jpg","Ose les interdits"],
	  ["SoMa_08.jpg","Change d’univers graphique"],
	  ["SoMa_09.jpg","Laisse reposer ton design et reviens dans 3 jours"],
	  ["SoMa_10.jpg","Sors des tendances"],
		["SoMa_11.jpg","Dans l’obscurité totale"],
	  ["SoMa_12.jpg","Copie pour apprendre"],
	  ["SoMa_13.jpg","Imagine une chenille en mouvement"],
	  ["SoMa_14.jpg","Reviens sur ton design"],
	  ["SoMa_15.jpg","Confronte toi aux avis extérieurs"],
		["SoMa_16.jpg","Visite une exposition"],
	  ["SoMa_17.jpg","Ne sois pas trop illustratif"],
	  ["SoMa_18.jpg","Déforme ta typographie"],
	  ["SoMa_19.jpg","Demande à ta maman"],
	  ["SoMa_20.jpg","Déplace tout de 2 cm"],

	];
